2019-05-14 02:55:41,894 - get_attachment - ERROR - EXCEPTION OCCURED: 'NoneType' object has no attribute 'find'
2019-05-14 02:55:41,921 - get_attachment - ERROR - Traceback (most recent call last):
  File "C:\Users\vimanyua\PycharmProjects\Pipeline\skills_data\get_attachment.py", line 99, in save_attachment
    if part.get('Content-Disposition').find(BASEFILE) == -1:
AttributeError: 'NoneType' object has no attribute 'find'

2019-05-14 02:55:41,922 - get_attachment - ERROR - EXCEPTION OCCURED: 'NoneType' object has no attribute 'find'
2019-05-14 02:55:41,922 - get_attachment - ERROR - Traceback (most recent call last):
  File "C:\Users\vimanyua\PycharmProjects\Pipeline\skills_data\get_attachment.py", line 99, in save_attachment
    if part.get('Content-Disposition').find(BASEFILE) == -1:
AttributeError: 'NoneType' object has no attribute 'find'

